language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy philong996/reverseproxy:$VERSION
  - docker tag udagram-api-user philong996/udagram-api-user:$VERSION
  - docker tag udagram-api-feed philong996/udagram-api-feed:$VERSION
  - docker tag udagram-frontend:local philong996/udagram-frontend:$VERSION
  

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push philong996/reverseproxy:$VERSION
  - docker push philong996/udagram-api-user:$VERSION
  - docker push philong996/udagram-api-feed:$VERSION
  - docker push philong996/udagram-frontend:$VERSION